### ISSUE TITLE
Gamera hangs after adding a character to the classifier

### ISSUE THREAD

**Issue by jsbien** [hsnr-gamera/gamera-4#20] opened 2020-02-24 10:28 UTC
The message is repeated 27 times:
gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed
[hanglog_20-02-24.zip](https://github.com/hsnr-gamera/gamera-4/files/4244085/hanglog_20-02-24.zip)

If you wish to try to reproduce the problem: take myrealdata.zip from issue #14 and add the dotless i.

**Comment by cdalitz** [comment] 2021-04-14 10:27
While I get the GTK wanrings too, I cannot reproduce the hanging of the classifier interface. The Warnings seem to be a problem of the underlying GTK library, and it is reported by many wxPython users (actually tons of these warnings even occur with the examples from the wxPython tutorial):

[https://github.com/wxWidgets/Phoenix/issues/1297](https://github.com/wxWidgets/Phoenix/issues/1297)

As we have recently made some changes to gamera4: can you please test, whether the error still occurs, or whether we can close the issue?

Thanks for your patience.

**Closed** 2021-04-14 11:01 UTC

**Comment by jsbien** [comment] 2021-04-14 11:06
A lot of warnings and critical messages but despite of them the program seems to work. I will open news issues after additional experiments.
I'm glad gamera is again usable.
